# Generated by Django 3.0.5 on 2020-05-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Диагноз', max_length=200)),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.TextField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('position', models.TextField(blank=True, max_length=100, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Процедура', max_length=200)),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.TextField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('pulse_link', models.TextField(blank=True, max_length=150, verbose_name='Пульс')),
                ('spo2_link', models.TextField(blank=True, max_length=150, verbose_name='Содержание кислорода')),
                ('pi_link', models.TextField(blank=True, max_length=150, verbose_name='Перфузионный Индекс')),
                ('temperature_link', models.TextField(blank=True, max_length=150, verbose_name='Температура')),
                ('diagnosis', models.ManyToManyField(blank=True, help_text='Выберите диагноз', max_length=150, to='infirmary.Diagnosis')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infirmary.Doctor')),
                ('procedures', models.ManyToManyField(blank=True, help_text='Выберите процедуры', max_length=150, to='infirmary.Procedure')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
