# Generated by Django 3.0.5 on 2020-05-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='age',
            field=models.TextField(blank=True, max_length=100, verbose_name='Возраст'),
        ),
    ]
