# Generated by Django 3.0.5 on 2020-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0002_pacient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='age',
            field=models.CharField(blank=True, max_length=100, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='pi_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Перфузионный Индекс'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='pulse_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Пульс'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='spo2_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Содержание кислорода'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='temperature_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Температура'),
        ),
    ]
