# Generated by Django 3.0.5 on 2020-05-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0003_auto_20200525_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacient',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='pacient',
            name='diagnosis',
            field=models.ForeignKey(blank=True, help_text='Выберите диагноз', max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infirmary.Diagnosis'),
        ),
    ]
