# Generated by Django 3.0.5 on 2020-05-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0004_auto_20200525_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='pacient',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
