# Generated by Django 3.0.5 on 2020-05-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmary', '0005_auto_20200525_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
